### ISSUE TITLE
Update to the repo

### ISSUE THREAD

**Issue by ryanwoconnor** [chazeon/NYState-COVID-19-Tracker#2]
Can we get an update with the latest values here? Looks like data is outdated

**Comment by ret394** [comment]
update delay is good. see https://github.com/nychealth/coronavirus-data/issues/11#issuecomment-608426636

**Comment by ryanwoconnor** [comment]
Isn’t that a different git repository though?

**Comment by chazeon** [comment]
Do you mean state-level data? I just realized today that they have turned to Tableau system.

As the system seem to be much complicated, it will take some time to update the script.

**Comment by ryanwoconnor** [comment]
I’m actually keeping a close eye on the borough level data. It would be great to see those updates coming through again. I see a nice formatted table in your data folder. 

This data is typically locked away in PDF’s. 


https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary-deaths-04032020-2.pdf


https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary-04032020-2.pdf

**Comment by chazeon** [comment]
Thank you, I have only just realized they have changed the URL for these files recently. Script right not is not working. I will need to update the download script sometime later today. Thanks for the heads up!

**Comment by ryanwoconnor** [comment]
No problem! I would be very appreciative if you could. They did change the URL it looks like to include the date in the string.
