### ISSUE TITLE
convert python scripts

### ISSUE THREAD

**Issue by ret394** [chazeon/NYState-COVID-19-Tracker#3]
looked at https://github.com/chazeon/NYState-COVID-19-Tracker/tree/master/scripts
I don't know python and avoid it when I can.

is the code have good comments? I would like to get the files in another language.
I can't help a single bit with python.

got to find the right modules too.
https://github.com/chazeon/NYState-COVID-19-Tracker/blob/master/scripts/archive_map_nyc.py

**Comment by ret394** [comment]
got to find the right modules too.

**Comment by chazeon** [comment]
These code is not well commented because they are not built to last. These websites changes their formats almost weekly.
